apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: changeme
  namespace: openshift-config
spec:
  secretName: changeme
  duration: 2160h #90d
  renewBefore: 360h #15d
  dnsNames:
  - changeme
  issuerRef:
    name: changeme
    kind: ClusterIssuer
