apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: jason.horn@gmail.com
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: acme-issuer-account-key
    solvers:
    # this solver handles example.org challenges
    # and uses explicit credentials
    - selector:
        dnsZones:
          - changeme
      dns01:
        route53:
          region: us-east-1
          accessKeyID: changeme
          secretAccessKeySecretRef:
            name: changeme
            key: changeme
          # you can also assume a role with these credentials
          role: ""
