apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    alertmanagerMain:
      tolerations:
        - key: node-function
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    prometheusK8s:
      tolerations:
        - key: node-function
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    prometheusOperator:
      tolerations:
        - key: node-function
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    grafana:
      tolerations:
        - key: node-function
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    k8sPrometheusAdapter:
      tolerations:
        - key: node-function
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    kubeStateMetrics:
      tolerations:
        - key: node-function
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    telemeterClient:
      tolerations:
        - key: node-function
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
        remediationAction: enforce
        severity: low
