apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 50Gi
  nfs:
    path: /export
    server: 192.168.1.168
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
