apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: apps-the-jasonhorn-io
  namespace: openshift-ingress
spec:
  secretName: apps-the-jasonhorn-io
  duration: 2160h #90d
  renewBefore: 360h #15d
  dnsNames:
  - '*.apps.the.jasonhorn.io'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
