apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-key: AgDD2pt5Io3V45zlUtD5okrYjAc7wTYyR4vOyQ4w3CZXDR+FIZyn/Azf1ag6vu4tJ0AInR2AxG22uy936mImgPGdcv/7eeLH+h48FO9+Z7eE7iSUifnAhGhqw2iN1ItvbejdtvSWHpH397fDz5SEoUyE9HwdkEFAEc85UN1ma6EDr62AdkZu7oAuIDwrZM5xAyG8c28us2Hwwnw7cLJ7+ogoG0inlXetPo3x3JLOE/WONuwJawmweNUVmtP+Q94nmO27YlsTdf7lnZ85r6Q29qIiO0lOiuhdzic1HHcuRtnMuNyJChCHQ7KeFBArOZiLAfiUEJxT+V9Q8j5ieul5wBQnEMVJKvIyLKfGlkDubLn5A3sEi6nwBrNZ4lwtkA51T8CTWv64ag+kMCxpg2D9ijdF2V0nmDWfzfxr3kp5vIOQcyY50LT2OV6Pzi98Nx4Yurm7t2Gfq6dJWOCjlauXq8x+HLDpu2AacBY562ftI+udJAV5lK1l+rUudT3AbkgLTXQOBJfNv2dtAPkuBiKKzlM0W86RQJ11bEkF+qYnjNvvVCITCLGx7WVv7CMzvD67rernW4cAGDgUy2/xy4W/NH+RyS2OOmwkDSVXhNr/n/52mBzwOwvtlijzlPyhqAWrls7ISdv5qic36iUbz8qs04WvVv05ZFndbLFpLWDWD7eWlgIgiLnT4B+hOGuK7AAkk0JYIJ6B5TBDdD47anDF9SQ2HmNraOEh6ewadq+MhrgjPeg1QrsmtV1xYsn3IlV/
  template:
    metadata:
      creationTimestamp: null
      name: route53-secret
      namespace: cert-manager

