apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
   managementState: Managed
   replicas: 1
   logging: 2
   rolloutStrategy: Recreate
   tolerations:
   - key: node-function
     operator: Exists
     effect: NoSchedule
   nodeSelector:
       node-role.kubernetes.io/infra: "" 
   storage:
     pvc:
       claim: image-registry-pvc
