apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: idp-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCmheKiKXw0sZJBEHcOIHgKRaSqaOmK0/WhR96vKVjnmjaACAnm8ur81Lj+hkBi/5Npq0arGDf4expfVpvkf28XXGpx8uo/kOFurB/Iu+7QrzX+hgcokSDKXpGlOo6d/lZkUXaSFJHXu0Cus9jWC/6KGRfzIVhI0eg0LHizzam2qs+wUssNCPrhWEvSSkQRYOzJZ+6TULD7X9nbMjDwC3rc9pDCHoNpTwakBhUob8xY3dcjUyiJqGl0hd+eRFp4LmS/oRFa7b112lyAHvquHBXOcWqfuLjms3FP8oA8BIPSlYPDH9AWL2AW7P8sZJ0mklYvkJlORHgnzZOfT8sIp6u/D/zq402L47vBsD7ndmVU936WK/1LYMFinVRTdSBaEF+utp8aVkDTQZ/0LF5dzphlCUjv0TZyPAN0qwdGOpPcp+B90uxaCKJ0h8jv9NxQmU8Ph+gQMEa+QCO5TFfwwycA9JFo8SmvK2l9nL/C6Z4t5m1fIFfyQs/4ZRCVkU1bdACmjpb9PvXewQ+qlbGJnih3AzJnphwBkuSCDCf7gbn3kNhEhZ6T6MC/4F38zPdmeKDECii6RJnJ8C2K+dUX5ABXKbGWv3ZjSu/3bx6naOSZiXF9ojmZs59mUKgwIsOJL/oBzWgmnudPPwzzFPMY6jTwad6vFJglQJbj1z2gNGAuYObZRvyKN0IOFs+91r16YN4CmcuQXQq0Hs64Llg96wByiQ/X54U1dJw=
  template:
    metadata:
      creationTimestamp: null
      name: idp-secret
      namespace: openshift-config

