---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: git@github.com:redhat-cop/declarative-openshift.git
  labels:
    config.example.com/name: argocd-bootstrap
    config.example.com/component: operators
  name: argocd-operator
  namespace: argocd
spec:
  targetNamespaces:
  - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: git@github.com:redhat-cop/declarative-openshift.git
  labels:
    config.example.com/name: argocd-bootstrap
    config.example.com/component: operators
  name: argocd-operator
  namespace: argocd
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace 
