---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: git@github.com:redhat-cop/declarative-openshift.git
  labels:
    config.example.com/name: argocd-bootstrap
    config.example.com/component: namespaces
  name: argocd
spec:
