apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: idp-secret
  namespace: openshift-config
spec: 
  encryptedData:
    clientSecret: ""
  template:
    metadata:
      creationTimestamp: null
      name: idp-secret
      namespace: openshift-config

