apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-users-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://api.managed.foo.bar:6443'
  source:
    path: manifests/cluster-users/overlays/dev
    repoURL: 'https://github.com/hornjason/argocd-lab.git'
    targetRevision: demo
  project: default
  syncPolicy:
    automated: {}
